### ISSUE TITLE
tsc error in parse.ts

### ISSUE THREAD

**Issue by Eiryyy** [octet-stream/then-busboy#32]
```
> tsc

node_modules/then-busboy/@type/parse.d.ts:4:39 - error TS2503: Cannot find namespace 'busboy'.

4 export interface ParseOptions extends busboy.BusboyConfig {
                                        ~~~~~~


Found 1 error.

```

I couldn't build it because of this error, so I used -skipLibCheck

**Comment by octet-stream** [comment]
Hi! Sorry for a late response. I guess I might've need to add typings for busboy to `dependencies` section of my package.json instead of `devDependencies`. My huge mistake, sorry, I was new to TS that days. I will fix that.

See: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies

**Comment by octet-stream** [comment]
Okay, let's try this version in the wild: https://github.com/octet-stream/then-busboy/releases/tag/v5.1.2
I hope this will fix the issue.

**Comment by Eiryyy** [comment]
@octet-stream The problem has not yet been resolved.

We need to fix this part.
https://github.com/octet-stream/then-busboy/blob/103ec5180b051a56a3d0ae39c3c9989e1c0250fc/lib/parse.ts#L18-L24

Please check my PR https://github.com/octet-stream/then-busboy/pull/33

**Comment by octet-stream** [comment]
Yeah, it seems like it. Thanks for the PR. This should work.

**Comment by octet-stream** [comment]
Your fix is available in https://github.com/octet-stream/then-busboy/releases/tag/v5.1.3
